user_name: 'Polly'

# Must exist and contain the .cal file and a directory called 17_2
calibration_directory: 'P:\JoeRamsay\autoreduce\HRPD\Calibration'

# Must exist and contain a directory called 17_2
output_directory: 'P:\JoeRamsay\autoreduce\HRPD\Output'

# Put cycle_mapping.yaml in your HRPD folder
calibration_mapping_file: 'P:\JoeRamsay\autoreduce\HRPD\cycle_mapping.yaml'

do_absorb_corrections: False

vanadium_normalisation: True